apiVersion: v1
kind: Service
metadata:
  name: stats-backend
  labels:
    app: stats
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: stats
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-backend
  labels:
    app: stats
spec:
  selector:
    matchLabels:
      app: stats
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stats
        tier: backend
    spec:
      containers:
      - image: josoder/stats-backend
        name: backend-container
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
